---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: title
  label: title
  description: title
  hidden: false
  config:
    required: false
- type: textarea
  name: paragraph
  label: paragraph
  description: paragraph
pages:
- _posts/2018-10-08-hi-world.md
- test.md
